// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMS.Entities;

namespace TestMS.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20191011070518_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestMS.Entities.Menu", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Icon")
                        .HasMaxLength(50);

                    b.Property<long>("ParentId");

                    b.Property<int>("Sort");

                    b.Property<bool>("Spread");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TMS_Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
