// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMS.Entities;

namespace TestMS.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20200425145117_updateTablename")]
    partial class updateTablename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestMS.Entities.Enterprise", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Address")
                        .HasMaxLength(500);

                    b.Property<decimal>("BmapLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BmapLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Concentration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GPSLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GPSLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OrganCode")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TypeCode")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TMS_Enterprise");
                });

            modelBuilder.Entity("TestMS.Entities.Menu", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Icon")
                        .HasMaxLength(50);

                    b.Property<long>("ParentId");

                    b.Property<int>("Sort");

                    b.Property<bool>("Spread");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TMS_Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
